### ISSUE TITLE
FTP Service

### ISSUE THREAD

**Issue by qwo** [RubberDuckNFK/RubberDuckNFK#1]
Hi, 

I've been trying to connect to the ftp service. I checked yesterday and was unable and still am unable today.

Am I quacking this wrong?

**Comment by RubberDuckNFK** [comment]
I will look and get back to you

**Comment by RubberDuckNFK** [comment]
23.253.149.209

The A record wasn't created properly yesterday.. That's the IP, you can
also use ftp.rubberducknfk.com but may have to wait.

**Comment by qwo** [comment]
Perfect, it works thanks @RubberDuckNFK!

**Comment by RubberDuckNFK** [comment]
Stanley,

Just FYI, we are adding an additional front-facing camera hopefully
tomorrow.

Also, I'm thinking of coding some twilio integration so you can text the
duck and he'll take your picture and text it back to you, or post it to the
wall. What do you think.

**Comment by qwo** [comment]
very creative! 

Are you thinking like a duckcam/sign in book. Text a message to the duck and itll snap your pic and add it to a norfolk gallery on the rubberducknfk website?

a message attachment i believe might be rate limited (its been a while since i worked with twilio) 

so some express middleware that parses twilio msgs and grabs pics from the ftp service?

**Comment by RubberDuckNFK** [comment]
Yes..  exactly.. doing it now..  it'll just grab the ftp image at the
moment of the sms and add it to the facebook?  with the text of the sms as
a comment?  Or perhaps twitter?  that may be an easy way to get it it back
on the site.

**Comment by qwo** [comment]
I was thinking possibly a text triggers FTPing it into a folder gallery on the site that then gets photo galleried.  

Theres some middleware out there already to handle this and can be extensible to add share with facebook/twitter hooks later. 

https://github.com/cianclarke/node-gallery.git

What do you think?

**Comment by RubberDuckNFK** [comment]
Sounds good.  Can we auto share to our fb page too?

I'll check in the twilio code with a placeholder for you, if that helps.
 Going to play Skye's rubber ducky song when people make a voice call.
