### ISSUE TITLE
Twilio Integration

### ISSUE THREAD

**Issue by qwo** [RubberDuckNFK/RubberDuckNFK#3]
Call number (920) 75DUCKY to get a nice song.

Is the SMS/CapturePic idea still going on? 

I'm going to encouraged people at tonights Javascript meetup to hack on this project and would like to expose it to people. 

http://www.meetup.com/NorfolkJS/events/178440172/

**Comment by qwo** [comment]
@RubberDuckNFK if there are some issues you'd like to add , i'd recommend adding them before 6PM tonight. If theres a short term roadmap or useful feature list we will encourage folks to check issues :)

**Comment by RubberDuckNFK** [comment]
Did you get any bites at the meeting?  It's only here a few more days.  I'd like to do the sms thing, but not sure if I'll have time.

**Comment by qwo** [comment]
We pulled it up and I pitched it to the group at out last @norfolkjs Meetup, Ill bring it up also at @c4hrva tonight.

The site looks great and adding issues definitely encourages road map or what needs to be done.

Anyway looks awesome @RubberDuckNFK :)

**Comment by RubberDuckNFK** [comment]
Added twilo->facebook..  Getting really lonely around here :(

**Comment by qwo** [comment]
Sorry @RubberDuckNFK, planning large scale event and working on another hack project right now. Will try to give it a piece of time this weekend.

A common feedback I'm getting is "what is there to be done, what is there to be hacked". Maybe a roadmap or some feature issues could help drive hackers.

Some @norfolkjs love for the #chryslerquacker ;(?

**Comment by qwo** [comment]
pinging @757rb @hrnug @hrphp @c4hrva

**Comment by RubberDuckNFK** [comment]
Right!  We've been so busy we do need to add some direction.. will add some
ideas issues tonight.:)

**Comment by qwo** [comment]
Sweet good deal!

On Thu, May 22, 2014 at 3:21 PM, RubberDuckNFK notifications@github.comwrote:

> Right! We've been so busy we do need to add some direction.. will add some
> ideas issues tonight.:)
> 
> On Thu, May 22, 2014 at 3:14 PM, Stanley Zheng notifications@github.comwrote:
> 
> > pinging @757rb https://github.com/757rb @hrnnug @hrphp<
> > https://github.com/hrphp>
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/RubberDuckNFK/RubberDuckNFK/issues/3#issuecomment-43931764>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/RubberDuckNFK/RubberDuckNFK/issues/3#issuecomment-43932606
> .
> 
> ---
> 
> Spamhttps://www.spamtrap.odu.edu/canit/b.php?i=02M57m7zj&m=656782626362&t=20140522&c=s
> Not spamhttps://www.spamtrap.odu.edu/canit/b.php?i=02M57m7zj&m=656782626362&t=20140522&c=n
> Forget previous votehttps://www.spamtrap.odu.edu/canit/b.php?i=02M57m7zj&m=656782626362&t=20140522&c=f

## 

Stanley Zheng
@stanzheng http://twitter.com/stanzheng
